//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbxUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbxUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string PasswordDialog_Cancel {
            get {
                return ResourceManager.GetString("PasswordDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入密码 的本地化字符串。
        /// </summary>
        internal static string PasswordDialog_EnterPassword {
            get {
                return ResourceManager.GetString("PasswordDialog_EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string PasswordDialog_OK {
            get {
                return ResourceManager.GetString("PasswordDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位不可转换 的本地化字符串。
        /// </summary>
        internal static string UnconvertibleUnits {
            get {
                return ResourceManager.GetString("UnconvertibleUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 厘米 的本地化字符串。
        /// </summary>
        internal static string Units_Centimeters_Long {
            get {
                return ResourceManager.GetString("Units_Centimeters_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 厘米 的本地化字符串。
        /// </summary>
        internal static string Units_Centimeters_Short {
            get {
                return ResourceManager.GetString("Units_Centimeters_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英寸 的本地化字符串。
        /// </summary>
        internal static string Units_Feet_Long {
            get {
                return ResourceManager.GetString("Units_Feet_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英寸 的本地化字符串。
        /// </summary>
        internal static string Units_Feet_Short {
            get {
                return ResourceManager.GetString("Units_Feet_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英尺 的本地化字符串。
        /// </summary>
        internal static string Units_Inches_Long {
            get {
                return ResourceManager.GetString("Units_Inches_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英尺 的本地化字符串。
        /// </summary>
        internal static string Units_Inches_Short {
            get {
                return ResourceManager.GetString("Units_Inches_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公里 的本地化字符串。
        /// </summary>
        internal static string Units_Kilometers_Long {
            get {
                return ResourceManager.GetString("Units_Kilometers_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公里 的本地化字符串。
        /// </summary>
        internal static string Units_Kilometers_Short {
            get {
                return ResourceManager.GetString("Units_Kilometers_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 米 的本地化字符串。
        /// </summary>
        internal static string Units_Meters_Long {
            get {
                return ResourceManager.GetString("Units_Meters_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 米 的本地化字符串。
        /// </summary>
        internal static string Units_Meters_Short {
            get {
                return ResourceManager.GetString("Units_Meters_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英里 的本地化字符串。
        /// </summary>
        internal static string Units_Miles_Long {
            get {
                return ResourceManager.GetString("Units_Miles_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公里 的本地化字符串。
        /// </summary>
        internal static string Units_Miles_Short {
            get {
                return ResourceManager.GetString("Units_Miles_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毫米 的本地化字符串。
        /// </summary>
        internal static string Units_Millimeters_Long {
            get {
                return ResourceManager.GetString("Units_Millimeters_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 毫米 的本地化字符串。
        /// </summary>
        internal static string Units_Millimeters_Short {
            get {
                return ResourceManager.GetString("Units_Millimeters_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弧度 的本地化字符串。
        /// </summary>
        internal static string Units_Radians_Long {
            get {
                return ResourceManager.GetString("Units_Radians_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位不可识别 的本地化字符串。
        /// </summary>
        internal static string UnrecognizedUnits {
            get {
                return ResourceManager.GetString("UnrecognizedUnits", resourceCulture);
            }
        }
    }
}
